name: TEST - expo-updates mode

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        type: string
      config:
        description: 'Config (default-devices, all-devices, many-stories)'
        required: false
        default: 'default-devices'
        type: string
      project:
        description: 'Project (expo-updates, device-testing, many-stories)'
        required: true
        type: string
      with_builds:
        description: 'With builds'
        required: false
        default: false
        type: boolean

jobs:
  run_sherlo_expo_update:
    name: Run Sherlo in expo-updates mode
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn switch-env:${{ inputs.env }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Trigger EAS update and capture manifest URLs
        working-directory: testing/expo-storybook-8
        run: |
          # new flow
          # echo "EXPO_UPDATE_JSON=$(eas update --channel 'development' --message 'Expo Update' --json --non-interactive | jq -c .)" >> $GITHUB_ENV
          # old flow
          EXPO_UPDATE_JSON=$(eas update --channel "development" --message "Expo Update ${GITHUB_SHA}" --json --non-interactive)
          echo "ANDROID_EXPO_UPDATE_URL=$(echo "$EXPO_UPDATE_JSON" | jq -r '.[] | select(.platform == "android") | .manifestPermalink')" >> $GITHUB_ENV
          echo "IOS_EXPO_UPDATE_URL=$(echo "$EXPO_UPDATE_JSON" | jq -r '.[] | select(.platform == "ios") | .manifestPermalink')" >> $GITHUB_ENV

      - name: Run sherlo expo-updates (with native builds)
        if: inputs.with_builds == true
        working-directory: testing/expo-storybook-8
        run: |
          yarn sherlo expo-updates \
            --config ../../configs/${{ inputs.config }}.json \
            --android builds/development/android.apk \
            --ios builds/development/ios.tar.gz \
            --androidUpdateUrl ${{ env.ANDROID_EXPO_UPDATE_URL }} \
            --iosUpdateUrl ${{ env.IOS_EXPO_UPDATE_URL }} \
            --token ${{ inputs.project == 'expo-updates' && secrets.SHERLO_EXPO_UPDATE_TOKEN || inputs.project == 'many-stories' && secrets.SHERLO_MANY_STORIES_TOKEN || inputs.project == 'device-testing' && secrets.SHERLO_ALL_DEVICES_TOKEN }}

      - name: Run sherlo expo-updates (without native builds)
        if: inputs.with_builds == false
        working-directory: testing/expo-storybook-8
        run: |
          yarn sherlo expo-updates \
            --config ../../configs/${{ inputs.config }}.json \
            --androidUpdateUrl ${{ env.ANDROID_EXPO_UPDATE_URL }} \
            --iosUpdateUrl ${{ env.IOS_EXPO_UPDATE_URL }} \
            --token ${{ inputs.project == 'expo-updates' && secrets.SHERLO_EXPO_UPDATE_TOKEN || inputs.project == 'many-stories' && secrets.SHERLO_MANY_STORIES_TOKEN || inputs.project == 'device-testing' && secrets.SHERLO_ALL_DEVICES_TOKEN }}
