name: TEST - expo-cloud-builds mode

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        type: string
      use_github_action:
        description: 'Use Sherlo Github Action'
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        default: 'dev'
        type: string
      use_github_action:
        description: 'Use Sherlo Github Action'
        required: false
        type: boolean
        default: false

jobs:
  start_sherlo_expo_cloud:
    if: >
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && startsWith(github.event.label.name, 'sherlo:eas')) ||
      (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add env specific dependencies
        run: yarn switch-env:${{ inputs.env }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Install project dependencies
        working-directory: testing/expo-storybook-8
        run: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # It's important to run Sherlo in the same job as the EAS build,
      # because we're pushing temporary files to .expo directory used during the build
      - name: Run sherlo expo-cloud-builds with CLI
        if: inputs.use_github_action == false
        working-directory: testing/expo-storybook-8
        run: |
          yarn sherlo expo-cloud-builds \
            --waitForEasBuild \
            --config ../../configs/default-devices.json \
            --token ${{ secrets.SHERLO_EXPO_CLOUD_TOKEN }}

      - name: Run sherlo expo-cloud-builds with Github Action
        if: inputs.use_github_action == true
        uses: ./.
        with:
          command: expo-cloud-builds
          projectRoot: testing/expo-storybook-8
          waitForEasBuild: true
          config: ../../configs/default-devices.json
        env:
          SHERLO_TOKEN: ${{ secrets.SHERLO_EXPO_CLOUD_TOKEN }}

      - name: Trigger EAS builds for both platforms
        working-directory: testing/expo-storybook-8
        run: eas build --profile=preview --platform=all --non-interactive --no-wait
