name: TEST - expo-update mode

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        type: string
      with_builds:
        description: 'With builds'
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        default: 'dev'
        type: string
      with_builds:
        description: 'With builds'
        required: false
        default: false
        type: boolean
jobs:
  run_sherlo_expo_update:
    name: Run Sherlo in expo-update mode
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn

      - name: Build dependencies
        run: yarn switch-env:${{ inputs.env }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Trigger EAS update and capture manifest URLs
        working-directory: testing/expo-storybook-8
        run: |
          # Store the JSON in a file first to handle potential special characters
          eas update --channel "development" --message "Expo Update ${GITHUB_SHA}" --json --non-interactive > update_output.json
          
          # Set environment variables using the file
          echo "EXPO_UPDATE_JSON=$(cat update_output.json)" >> $GITHUB_ENV
          echo "ANDROID_EXPO_UPDATE_URL=$(cat update_output.json | jq -r '.[] | select(.platform == "android") | .manifestPermalink')" >> $GITHUB_ENV
          echo "IOS_EXPO_UPDATE_URL=$(cat update_output.json | jq -r '.[] | select(.platform == "ios") | .manifestPermalink')" >> $GITHUB_ENV

      - name: Run sherlo expo-update (with native builds)
        if: inputs.with_builds == true
        run: |
          yarn sherlo expo-update \
            --config configs/default-devices.json \
            --android testing/expo-storybook-8/builds/development/android.apk \
            --androidUrl ${{ env.ANDROID_EXPO_UPDATE_URL }} \
            --ios testing/expo-storybook-8/builds/development/ios.tar.gz \
            --iosUrl ${{ env.IOS_EXPO_UPDATE_URL }} \
            --token ${{ secrets.SHERLO_EXPO_UPDATE_TOKEN }}

      - name: Run sherlo expo-update (without native builds)
        if: inputs.with_builds == false
        run: |
          yarn sherlo expo-update \
            --config configs/default-devices.json \
            --androidUrl ${{ env.ANDROID_EXPO_UPDATE_URL }} \
            --iosUrl ${{ env.IOS_EXPO_UPDATE_URL }} \
            --token ${{ secrets.SHERLO_EXPO_UPDATE_TOKEN }}

# --expoUpdateJson ${{ env.EXPO_UPDATE_JSON }}
