name: TEST - local-builds mode (Expo)

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        type: string
      use_github_action:
        description: 'Use Sherlo Github Action'
        required: false
        type: boolean
        default: false
      project:
        description: 'Project (expo-storybook-8, rn-storybook-7)'
        required: true
        type: string
        default: 'expo-storybook-8'
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        default: 'dev'
        type: string
      use_github_action:
        description: 'Use Sherlo Github Action'
        required: false
        type: boolean
        default: false
      project:
        description: 'Project (expo-storybook-8, rn-storybook-7)'
        required: true
        type: string
        default: 'expo-storybook-8'
jobs:
  sherlo_local_builds:
    name: Run sherlo local-builds (expo)
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: yarn

      - name: Add env specific dependencies
        run: yarn switch-env:${{ inputs.env }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Install project dependencies
        working-directory: testing/${{ inputs.project }}
        run: yarn

      - name: Run sherlo local-builds with CLI
        if: inputs.use_github_action == false
        working-directory: testing/${{ inputs.project }}
        run: |
          yarn sherlo local-builds \
            --config ../../configs/default-devices-without-expo-info.json \
            --android builds/preview/android.apk \
            --ios builds/preview/ios.tar.gz \
            --token ${{ inputs.project == 'expo-storybook-8' && secrets.SHERLO_LOCAL_BUILDS_EXPO_TOKEN || inputs.project == 'rn-storybook-7' && secrets.SHERLO_LOCAL_BUILDS_RN_TOKEN }}

      - name: Run sherlo local-builds with Github Action
        if: inputs.use_github_action == true
        uses: ./.
        with:
          command: local-builds
          projectRoot: testing/${{ inputs.project }}
          config: ../../configs/default-devices-without-expo-info.json
          android: builds/preview/android.apk
          ios: builds/preview/ios.tar.gz
        env:
          SHERLO_TOKEN: ${{ inputs.project == 'expo-storybook-8' && secrets.SHERLO_LOCAL_BUILDS_EXPO_TOKEN || inputs.project == 'rn-storybook-7' && secrets.SHERLO_LOCAL_BUILDS_RN_TOKEN }}
