name: 'test:eas-cloud-build'

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        type: string

jobs:
  test_eas_cloud_build:
    if: >
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && startsWith(github.event.label.name, 'sherlo:eas')) ||
      (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add env specific dependencies
        run: ./scripts/switch-env.sh ${{ inputs.env }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Install dependencies
        run: yarn && cd packages/cli && yarn build

      - name: Install project dependencies
        working-directory: testing/expo
        run: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # It's important to run Sherlo in the same job as the EAS build,
      # because we're pushing temporary files to .expo directory used during the build
      - name: Run sherlo test:eas-cloud-build with CLI
        working-directory: testing/expo
        run: |
          yarn sherlo test:eas-cloud-build \
            --waitForEasBuild \
            --config ../../configs/default-devices-without-expo-info.json \
            --token ${{ secrets.SHERLO_EAS_CLOUD_TOKEN }}

      - name: Trigger EAS builds for both platforms
        working-directory: testing/expo
        run: eas build --profile=preview --platform=all --non-interactive --no-wait
