name: 'test:standard'

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment (dev, test, prod)'
        required: true
        type: string
      project:
        description: 'Project (expo, react-native)'
        required: true
        type: string
        default: 'expo'
      arch:
        description: 'Architecture to use (old, new)'
        required: false
        default: 'old'
        type: string

jobs:
  test_standard:
    name: Run Sherlo in standard mode
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Add env specific dependencies
        run: ./scripts/switch-env.sh ${{ inputs.env }}
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Install dependencies
        run: yarn && cd packages/cli && yarn build

      - name: Install project dependencies
        working-directory: testing/${{ inputs.project }}
        run: yarn

      - name: Download builds
        run: ./scripts/downloadBuilds.sh --project ${{ inputs.project }} --profile preview-${{ inputs.arch }} --branch ${{ github.head_ref || github.ref_name }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run sherlo test:standard with CLI
        working-directory: testing/${{ inputs.project }}
        run: |
          yarn sherlo test:standard \
            --config ../../configs/default-devices-without-expo-info.json \
            --android builds/preview-${{ inputs.arch }}/android.apk \
            --ios builds/preview-${{ inputs.arch }}/ios.tar.gz \
            --token ${{ (inputs.project == 'expo' && inputs.arch == 'old' && secrets.SHERLO_STANDARD_EXPO_OLD_TOKEN) || 
                        (inputs.project == 'expo' && inputs.arch == 'new' && secrets.SHERLO_STANDARD_EXPO_NEW_TOKEN) || 
                        (inputs.project == 'react-native' && inputs.arch == 'old' && secrets.SHERLO_STANDARD_RN_OLD_TOKEN) || 
                        (inputs.project == 'react-native' && inputs.arch == 'new' && secrets.SHERLO_STANDARD_RN_NEW_TOKEN) }}
